version: '3.9'  # Docker Compose version

services:
  auth-service:
    build: ./auth-service  # Path to the Dockerfile
    ports:
      - "3001:3001"  # Expose port 3000 on host
    #environment:
    #  - NODE_ENV=development
    #  - MONGO_URI=mongodb://mongodb:27017/microservice_a_db  # MongoDB connection string
    #networks:
    #  - microservices-network

  users-service:
    build: ./users-service
    ports:
      - "3002:3002"
    #environment:
    #  - MONGODB_URI="mongodb+srv://admin:Turiba333@cluster0.wkfnyom.mongodb.net/LMS?retryWrites=true&w=majority&appName=Cluster0"
    #  - JWT_SECRET=""
    #  - PORT="3002"
    #  - NODE_ENV=development
    #networks:
    #  - microservices-network
