version: '3.9'  # Docker Compose version


services:

  traefik:
    image: traefik:v3.0  # Traefik version
    command: 
    - "--api.insecure=true"
    - "--providers.docker"
    ports:
      - "80:80"  # Expose HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Traefik to interact with Docker

  auth-service:
    build: ./auth-service  # Path to the Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/api/auth`)" 
    env_file:
      - ./auth-service/.env
    image: auth-service:latest

  learning-service:
    build: ./learning-service  # Path to the Dockerfile
    labels:
      - "traefik.enable=true"
     # - "traefik.http.middlewares.learning-service.forwardauth.address=http://auth-service:3001/api/auth/validation/jwt"
     # - "traefik.http.routers.learning-service.middlewares=learning-service@docker"
      - "traefik.http.routers.learning-service.rule=PathPrefix(`/api/learning`)"
    env_file:
      - ./learning-service/.env
    image: learning-service:latest
