version: '3.9'  # Docker Compose version


services:

  traefik:
    image: traefik:v3.0  # Traefik version
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"  # Expose HTTP port
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Traefik to interact with Docker

  auth-service:
    build: ./auth-service  # Path to the Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=Host(`auth.localhost`)" 
    env_file:
      - .env
